export type Locale = "zh" | "en";

const graphTermMap = {
  Company: { zh: "公司", en: "Company" },
  Event: { zh: "事件", en: "Event" },
  Product: { zh: "产品", en: "Product" },
  Source: { zh: "来源", en: "Source" },
  Organization: { zh: "组织", en: "Organization" },
  Person: { zh: "人物", en: "Person" },
  INVOLVED_IN: { zh: "参与事件", en: "INVOLVED_IN" },
  LAUNCHED: { zh: "发布了", en: "LAUNCHED" },
  PARTNERED_WITH: { zh: "合作对象", en: "PARTNERED_WITH" },
  REPORTED_BY: { zh: "报道来源", en: "REPORTED_BY" },
  product_launch: { zh: "产品发布", en: "Product Launch" },
  partnership: { zh: "合作签约", en: "Partnership" },
  earnings: { zh: "财报业绩", en: "Earnings" },
  acquisition: { zh: "并购交易", en: "Acquisition" },
  leadership_change: { zh: "高管变动", en: "Leadership Change" },
  regulation: { zh: "监管事件", en: "Regulation" },
  news: { zh: "一般动态", en: "General Update" },
  "Product Launch": { zh: "产品发布", en: "Product Launch" },
  Partnership: { zh: "合作签约", en: "Partnership" },
  Earnings: { zh: "财报业绩", en: "Earnings" },
  Acquisition: { zh: "并购交易", en: "Acquisition" },
  "Leadership Change": { zh: "高管变动", en: "Leadership Change" },
  Regulation: { zh: "监管事件", en: "Regulation" },
  "General Update": { zh: "一般动态", en: "General Update" },
  "Press Release": { zh: "官方新闻稿", en: "Press Release" },
  "Industry News": { zh: "行业媒体", en: "Industry News" },
  "Google News RSS": { zh: "Google 新闻 RSS", en: "Google News RSS" },
  langchain: { zh: "LangChain", en: "LangChain" },
  rules: { zh: "规则生成", en: "Rules" },
  high: { zh: "高", en: "High" },
  medium: { zh: "中", en: "Medium" },
  low: { zh: "低", en: "Low" }
} satisfies Record<string, Record<Locale, string>>;

export function translateGraphTerm(value: string, locale: Locale): string {
  return graphTermMap[value]?.[locale] ?? value;
}

export function formatTopEventTypes(eventTypes: string[], locale: Locale): string {
  if (eventTypes.length === 0) {
    return locale === "zh" ? "暂无" : "None";
  }
  return eventTypes.map((item) => translateGraphTerm(item, locale)).join(", ");
}

export function formatFieldLabel(field: string, locale: Locale): string {
  const labels: Record<string, Record<Locale, string>> = {
    event_type: { zh: "事件类型", en: "Event Type" },
    event_label: { zh: "事件标签", en: "Event Label" },
    date: { zh: "日期", en: "Date" },
    published_date: { zh: "发布日期", en: "Published Date" },
    summary: { zh: "摘要", en: "Summary" },
    title: { zh: "标题", en: "Title" },
    article_title: { zh: "新闻标题", en: "Article Title" },
    article_snippet: { zh: "新闻摘要", en: "Article Snippet" },
    article_count: { zh: "新闻数量", en: "Article Count" },
    article_titles: { zh: "新闻标题列表", en: "Article Titles" },
    articles: { zh: "新闻列表", en: "Articles" },
    key_points: { zh: "关键要点", en: "Key Points" },
    confidence: { zh: "置信度", en: "Confidence" },
    generated_by: { zh: "生成方式", en: "Generated By" },
    raw_llm_output: { zh: "原始 LLM 返回", en: "Raw LLM Output" },
    canonical_name: { zh: "标准名称", en: "Canonical Name" },
    company_name: { zh: "目标公司", en: "Company" },
    source_name: { zh: "来源名称", en: "Source Name" },
    source_url: { zh: "来源链接", en: "Source URL" },
    url: { zh: "链接", en: "URL" },
    published_at: { zh: "发布时间", en: "Published At" }
  };
  return labels[field]?.[locale] ?? field;
}

export const messages = {
  zh: {
    appName: "公司事件图谱",
    heroTitle: "用图谱方式追踪公司最近动态。",
    heroDescription:
      "输入公司名称和时间范围，抓取相关新闻与公告，抽取结构化事件与关系，并以可追溯证据的方式展示结果。",
    companyLabel: "公司名称",
    companyPlaceholder: "例如：Tesla",
    timeRangeLabel: "时间范围",
    runResearch: "开始研究",
    running: "研究中...",
    targetCompany: "目标公司",
    eventCount: "事件数量",
    sourceCount: "来源数量",
    topTypes: "主要类型",
    topTypesValue: "暂无",
    aiStatus: "AI 状态",
    aiEnabled: "已使用 AI",
    aiDisabled: "未使用 AI",
    aiMixed: "部分使用 AI",
    aiProvider: "AI 提供方",
    aiReason: "未使用 AI 原因",
    taskHistory: "历史任务",
    loadTask: "载入任务",
    noTasks: "还没有历史任务，先运行一次研究任务。",
    graphTitle: "图谱预览",
    graphDescription:
      "图谱区域已接入 Cytoscape.js，可直接查看节点、关系和结构分布。",
    nodes: "节点",
    edges: "关系",
    language: "语言",
    chinese: "中文",
    english: "英文",
    startDate: "开始日期",
    endDate: "结束日期",
    statusIdle: "填写公司名称和时间范围后开始研究。",
    statusLoading: "正在调用后端接口并生成图谱数据。",
    statusSuccess: "已返回任务结果，可以继续替换为真实新闻源和图数据库。",
    statusError: "请求失败，请确认后端是否已启动。",
    noGraph: "还没有图数据，先运行一次研究任务。",
    details: "详情",
    selectHint: "点击图中的节点或关系，可以在这里查看详情。",
    sourceLink: "打开来源",
    relationPath: "关系路径",
    eventInfo: "事件信息",
    sourceInfo: "来源信息",
    rawData: "原始数据",
    relatedArticles: "相关新闻",
    aiSummary: "AI 事件总结"
  },
  en: {
    appName: "Company Event Graph",
    heroTitle: "Track recent company dynamics as a graph.",
    heroDescription:
      "Input a company name and time range, fetch recent news and disclosures, extract structured events and relations, and present the result with traceable evidence.",
    companyLabel: "Company",
    companyPlaceholder: "e.g. Tesla",
    timeRangeLabel: "Time Range",
    runResearch: "Run Research",
    running: "Running...",
    targetCompany: "Target Company",
    eventCount: "Events",
    sourceCount: "Sources",
    topTypes: "Top Types",
    topTypesValue: "None",
    aiStatus: "AI Status",
    aiEnabled: "AI Used",
    aiDisabled: "No AI",
    aiMixed: "Mixed",
    aiProvider: "AI Provider",
    aiReason: "Why AI Was Not Used",
    taskHistory: "Task History",
    loadTask: "Load Task",
    noTasks: "No saved tasks yet. Run a research task first.",
    graphTitle: "Graph Preview",
    graphDescription:
      "The graph area is powered by Cytoscape.js and already renders nodes and relations interactively.",
    nodes: "Nodes",
    edges: "Edges",
    language: "Language",
    chinese: "Chinese",
    english: "English",
    startDate: "Start Date",
    endDate: "End Date",
    statusIdle: "Enter a company name and time range to start research.",
    statusLoading: "Calling the backend API and generating graph data.",
    statusSuccess: "The task result is ready. You can replace the mock pipeline with real data sources next.",
    statusError: "Request failed. Check whether the backend server is running.",
    noGraph: "No graph data yet. Run a research task first.",
    details: "Details",
    selectHint: "Click a node or edge in the graph to inspect its details here.",
    sourceLink: "Open Source",
    relationPath: "Relation Path",
    eventInfo: "Event Info",
    sourceInfo: "Source Info",
    rawData: "Raw Data",
    relatedArticles: "Related Articles",
    aiSummary: "AI Event Summary"
  }
} satisfies Record<Locale, Record<string, string>>;
